apiVersion: config.istio.io/v1beta1
kind: DestinationPolicy
metadata:
  name: sav-txn-circuit-breaker
spec:
  destination:
    name: saving-txn
    labels:
      version: v1
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      httpMaxPendingRequests: 1
      sleepWindow: 3m
      httpDetectionInterval: 500ms
      httpMaxEjectionPercent: 100
      httpConsecutiveErrors: 1
      httpMaxRequestsPerConnection: 1