apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: sav-txn-egress-pg
spec:
  destination:
    service: 172.20.102.48
  ports:
    - port: 31008
      protocol: tcp
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: sav-txn-egress-mongo
spec:
  destination:
    service: 172.20.102.48
  ports:
    - port: 31001
      protocol: mongo
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: sav-txn-egress-redis
spec:
  destination:
    service: 172.20.102.48
  ports:
    - port: 31005
      protocol: tcp