# this file for deployment report
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: report
  labels:
    run: report
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: report
    spec:
      containers:
      - name: report
        image: tnindo/report:v1stag.0.5
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/supervisor/conf.d
          name: report-vol
        - mountPath: /go/src/report/logs
          name: report-logs
        env:
        - name: GOPATH
          value: "/go"
        - name: GOAPP
          value: "report"
        - name: GOENV
          value: "kube"
        - name: SMITHBANKID
          value: "009"
        - name: HTTP
          value: "kube"
        - name: RPC
          value: "kube"
        - name: CRED_MONGODB
          value: "mongodb://172.17.0.1:31001"
        - name: CRED_MQ
          value: "amqp://savrabbit:savrabbit@savrabbitmq:5672/"
        - name: CRED_PGSQL
          value: "postgres://postgres:root@172.17.0.1:31008/smith_report?sslmode=disable"
        - name: CRED_SQLITE
          value: ":memory:"
      restartPolicy: Always
      volumes:
      - name: report-vol
        hostPath:
          path: /home/ubuntu/saving_cred/report
      - name: report-logs
        hostPath:
          path: /data/saving_report/logs
      imagePullSecrets:
      - name: regsecret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

