apiVersion: v1
kind: Service
metadata:
  name: saving-redis
spec:
  type: NodePort
  selector:
    run: redis
  ports:
    - name: redisport
      port: 6379
      nodePort: 31005
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    run: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
      - name: redis
        image: redis
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
